---
- name: Manage underlay VXLAN static fdb entries
  hosts: vxlan
  become: true
  roles:
    - underlay-vxlan

- name: Deploy Thanos monitoring stack
  hosts: monitoring
  become: true
  roles:
    - thanos
